### ISSUE TITLE
Simplify cancel buttons

### ISSUE THREAD

**Issue by ybakos** [NikitaRubocki/ecotone-web#189]
Cancel buttons seems to have been extracted into:

1. A custom route, for generating cancel button URLs
2. A controller concern, to reduce duplication of `before` actions that handle redirects

There are a few problems with this approach.

1. The custom route should not be used. There is no RedirectCancelController. Instead, perhaps a simple helper method should be used. This also causes a problem in the feature test suite. See #158.
2. The form is using button to, because it seems a "button" is desired. But this embeds a form within a form, and this should be avoided. Instead, the visual Cancel buttons should just be simple links that are _styled_ to look like buttons. Because it is causing a  form submit is what seems to be driving the unconventional solution of redirecting a request to create/update that is intended to be cancelable.

In the end, none of this is necessary if the cancel button is a mere link and not an html `button`. (Rarely, if ever, use html `button`s.) I recommend removing the route, deleting the concern, and simplifying the views.

This should also resolve #158 .

**Comment by NikitaRubocki** [comment]
@ybakos can we discuss this at the next meeting or set up a meeting to discuss this issue? I'm going to need some Rails clarifications to undo these changes.

**Comment by ybakos** [comment]
We can @NikitaRubocki but it should be pretty simple. Here's a cancel button:

`= link_to 'Cancel', new_plant_sample_path, class: 'btn'`

Let's start there and post your question here...

**Comment by NikitaRubocki** [comment]
@ybakos  So, I had that going at first, but the problem is that it will just submit data.  So, say we are in an edit view.  If you change information and hit "Cancel" with that ^^ type of link/button, it will still submit the data to the database; it just thinks it's another submit button.  So my workaround was a redirect to a new path, which would hit before the submission to the database could happen.  Finally, I made the concern so the information was in one spot, instead of every single model view.

**Comment by ybakos** [comment]
@NikitaRubocki No, it doesn't. A link doesn't submit a form. I promise! :)

**Comment by NikitaRubocki** [comment]
@ybakos I can't figure out how to get the right path working when updating the cancel to a link.  It only stays on the page, instead of redirecting back to whatever page you started from.
